# Generated by Django 3.2.8 on 2021-10-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagging',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
