# Generated by Django 3.2.8 on 2021-10-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211023_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tagging',
            field=models.ManyToManyField(blank=True, related_name='taggings', to='api.Tag'),
        ),
    ]
