# Generated by Django 3.2.8 on 2021-10-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_response'),
        ('api', '0009_alter_post_tagging'),
    ]

    operations = [
    ]
