# Generated by Django 3.2.8 on 2021-10-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211024_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='post',
            name='response_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
