# Generated by Django 3.2.8 on 2021-10-25 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='response_count',
        ),
    ]
