# Generated by Django 3.2.8 on 2021-10-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
