# Generated by Django 3.2.8 on 2021-10-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_post_response_count'),
        ('api', '0014_user_title'),
    ]

    operations = [
    ]
