# Generated by Django 3.2.8 on 2021-10-26 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_0014_remove_post_response_count_0014_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='response',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='response',
            name='upvote',
        ),
        migrations.CreateModel(
            name='ResponseVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(1, 'Upvote'), (2, 'Downvote'), (3, 'Novote')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='response_comment_vote', to='api.response')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_vote', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(1, 'Upvote'), (2, 'Downvote'), (3, 'Novote')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_question_vote', to='api.post')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_question_vote', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(related_name='user_post_vote', through='api.QuestionVotes', to='api.User'),
        ),
        migrations.AddField(
            model_name='response',
            name='votes',
            field=models.ManyToManyField(related_name='user_response_vote', through='api.ResponseVote', to='api.User'),
        ),
    ]
