# Generated by Django 3.2.8 on 2021-10-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211026_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionvotes',
            name='vote_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'upvote'), (2, 'downvote'), (3, 'novote')], default=3),
        ),
        migrations.AlterField(
            model_name='responsevote',
            name='vote_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'upvote'), (2, 'downvote'), (3, 'novote')], default=3),
        ),
    ]
