# Generated by Django 3.2.8 on 2021-11-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211109_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
