# Generated by Django 3.2.8 on 2021-11-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_questionflag_responseflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionflag',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'safe'), (3, 'quarantined')], default=1),
        ),
        migrations.AddField(
            model_name='responseflag',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'safe'), (3, 'quarantined')], default=1),
        ),
    ]
