# Generated by Django 3.2.8 on 2021-11-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20211113_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionflag',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'safe'), (2, 'quarantined')], default=0),
        ),
        migrations.AlterField(
            model_name='responseflag',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'safe'), (2, 'quarantined')], default=0),
        ),
    ]
