# Generated by Django 3.2.8 on 2021-11-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20211113_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quarantine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='quarantine',
            field=models.BooleanField(default=False),
        ),
    ]
